resources:
  - name: ddRepo
    type: GitRepo
    configuration:
      gitProvider: aem_test
      path: Tech314/D-D-Party-Platform
      branches:
        include: master        
  - name: art
    type: BuildInfo
    configuration:
      sourceArtifactory: test
pipelines:  
  - name: build_pipe
    steps:
      - name: step_1
        type: MvnBuild
        configuration:
          inputResources:
            - name: ddRepo  
          mvnCommand: clean install
          forceXrayScan: true
          failOnScan: false
          integrations:
            - name: test
        execution:
          onStart:
            - echo "Building..."
